runtime: python37
service: archive

handlers:
- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt
  secure: always
  redirect_http_response_code: 301
  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
